### ISSUE TITLE
TODO : Porting libhugetlbfs from autotest to avocado

### ISSUE THREAD

**Issue by santhosh93** [avocado-framework/avocado-misc-tests#11]
I am working on porting libhugetlbfs from autotest to avocado,
link - 'https://github.com/autotest/autotest-client-tests/tree/master/libhugetlbfs'

While porting I am facing an issue here in,

utils.check_kernel_ver("2.6.16")   ---- > libhugetlbfs.py in autotest-client-tests/

this method checks whether the kernel version is above 2.6.16 .

In avocado, I did not get similar functionality. If I want to achieve the same thing here in avocado, which is the exact location where I could implement the functionality so that I can use in my tests  or should I handle this in my test only..?

**Comment by apahim** [comment]
If you see this function as something that will be needed in the future by other tests, you can create a module in main avocado repository, under `avocado/utils/` directory, and use it in your test with `from avocado.utils import my_new_module`.

**Comment by santhosh93** [comment]
@apahim: Thanks for your suggestion.

**Comment by ldoktor** [comment]
This repository is frozen, please re-raise this issue in https://github.com/avocado-framework-tests/avocado-misc-tests if still valid.
