### ISSUE TITLE
TODO: Porting parallel_dd from autotest to avocado

### ISSUE THREAD

**Issue by rajashreer7** [avocado-framework/avocado-misc-tests#21]
I am working on porting parallel_dd from autotest to avocado,
link - "https://github.com/autotest/autotest-client-tests/tree/master/parallel_dd"

While porting I have a few doubts,

fs = job.filesystem('/dev/sda3', job.tmpdir)
In control file this method has been used, which is not available in avocado.

Similarly in parallel_dd.py in autotest-client-tests/, 
         fs.mkfs(fstype)
         fs.mount(None)
         fs.unmount()

 In avocado these functionalities are not available. Can I implement these functionalities as common utilities to avocado, so that I can use in my test?

**Comment by ldoktor** [comment]
Yes, that would be appreciated. I took a quick glance at that and it'll require some refactorings and cleanups for inclusion in avocado. Basically you should implement a stripped-out version and please do include the reference to the original code (autotest).

**Comment by rajashreer7** [comment]
@ldoktor: Thanks for your suggestion.

**Comment by ldoktor** [comment]
This repository is frozen, please re-raise this issue in https://github.com/avocado-framework-tests/avocado-misc-tests if still valid.
