### ISSUE TITLE
TODO: Porting lvsetup form autotest to avocado

### ISSUE THREAD

**Issue by harish-24** [avocado-framework/avocado-misc-tests#30]
I am porting lvsetup.

I see `@error.context_aware` is used in autotest https://github.com/autotest/autotest/blob/master/client/lv_utils.py. Is there anything close to it in avocado or python unittest?

Refered https://github.com/autotest/autotest/blob/master/client/shared/error.py for its functionality.

**Comment by ldoktor** [comment]
Hello @harish-24 the `@error.context_aware` is not implemented in avocado there is currently no plan in doing it. It was used for 2 things, the first is to know where the failure happened, but it's duplicate to `traceback` which does pretty much the same. The second feature of this was to log the executed steps, which was used by our QA a lot and this feature was replaced with separate logging streams: http://avocado-framework.readthedocs.io/en/latest/WritingTests.html#advanced-logging-capabilities
