### ISSUE TITLE
ffsb porting to avocado

### ISSUE THREAD

**Issue by kalshett** [avocado-framework/avocado-misc-tests#40]
I'm trying to port ffsb from autotest to avocado. Can someone comment on which folder we can add it? we can include under io/fs folder or we can add it under perf/io?

**Comment by clebergnu** [comment]
That's a tough call because ffsb falls in both categories (benchmark and filesystem).  I tend to think that the fact that it's related to filesystems is more relevant than the fact that it does benchmark, so I prefer the `io/fs` categorization.

**Comment by kalshett** [comment]
Agreed, will add under io/fs. Thx.
