### ISSUE TITLE
Including RAS tools in to avocado

### ISSUE THREAD

**Issue by Pavithra1602** [avocado-framework/avocado-misc-tests#42]
Hi,
I am working on getting RAS tools included in avocado for Power platform. Can I add them under "avocado-misctests/ras".

**Comment by ldoktor** [comment]
Dear @Pavithra1602,

that depends on the structure. If you're talking about RAS tool tests and if you expect many of them, then `avocado-misc-tests/ras` might be a suitable location. If you're talking about few tests, than maybe `avocado-misc-tests/misc/ras` or such.

If you're talking about the tools to handle RAS tools, then `avocado/utils/rastool` (or similar) would be the best place and you'd import this from your tests.

**Comment by ldoktor** [comment]
Actually I can see your PR https://github.com/avocado-framework/avocado-misc-tests/pull/53 so let's move the discussion there...
