### ISSUE TITLE
TODO: Porting cpu_hotplug from autotest to avocado

### ISSUE THREAD

**Issue by harish-24** [avocado-framework/avocado-misc-tests#64]
@ldoktor I am porting cpu_hotplug test from autotest to avocado.
Source: https://github.com/autotest/autotest-client-tests/blob/master/cpu_hotplug/cpu_hotplug.py

As the tar or git source is not maintained what would be the apt replacement for this?
https://github.com/autotest/autotest-client-tests/blob/master/cpu_hotplug/lhcs_regression-1.6.tgz

Or would it be okay to use the same tar?

**Comment by ldoktor** [comment]
Hello Harish,

that's a tough call. I'd prefer leaving the files outside the git repo, so I'd abuse the autotest's repo for it for now. But including is in the test's datadir is also an option.

Let's get more input on this: @adereis @apahim @clebergnu what would you recommend?

**Comment by ldoktor** [comment]
Btw I'm wondering if you use all the tests you're porting, or if you just backport all of them? I mean some of the tests were broken in autotest for years without notice...

**Comment by ldoktor** [comment]
This repository is frozen, please re-raise this issue in https://github.com/avocado-framework-tests/avocado-misc-tests if still valid.
