### ISSUE TITLE
TODO:Port linus_stress Test from autotest to avocado

### ISSUE THREAD

**Issue by PraveenPenguin** [avocado-framework/avocado-misc-tests#70]
I am working on porting linus_stress from autotest to avocado,
Link:"https://github.com/autotest/autotest-client-tests/blob/master/linus_stress"

While porting facing some issue 

profilers = self.job.profilers 
in autotest test code this function is used but in avocado i am not able get.

Similarly there are some more function which also not seems me available in avocado 
profilers.present()
profilers.start()
profilers.stop()
profilers.report()
utils.read_one_line()
utils.get_cc()

Can I implement these functionalities as common utilities to avocado, so able to use in my test?

**Comment by ldoktor** [comment]
Hello @PraveenPenguin, that's a good question. Avocado treats profilers in a different fashion, they are supported via `sysinfo` plugin and they are configured for all avocado executions the same. This is indeed quite different from autotest and I see there are tests which might benefit from being able to add or alter the configuration of related profilers (eg. increase the frequency).

@clebergnu you worked on the `sysinfo`, do you have any recommendations? Do we want to move the profilers from `core` to `utils` to being able to initialize them from test and report in test's results? That would IMO suit this purpose.

**Comment by PraveenPenguin** [comment]
@ldoktor thanks for looking in to this , one question 
utils.read_one_line()
utils.get_cc()
is this are also part of sysinfo

**Comment by ldoktor** [comment]
There is `avocado.utils.genio` for file handling, including `read_one_line`.

As for `get_cc` you should use `make` instead. It can be called without `Makefile` by specifying the result file: `make linus_stress` and it uses the `linus_stress.c` to produce the `linus_stress` binary. If you also want to use the flags, then you should use `CFLAGS=-D_POSIX_C_SOURCE=200112 make linus_stress` and the implicit rules produce the `linus_stress` out of the `linus_stress.c`.

**Comment by PraveenPenguin** [comment]
@clebergnu  i am trying to use profilers in one of the test (linus_stress)  but i am not able to see profilers.present() method in sysinfo can you please advise me in this .

Thanks

**Comment by ldoktor** [comment]
This repository is frozen, please re-raise this issue in https://github.com/avocado-framework-tests/avocado-misc-tests if still valid.
