### ISSUE TITLE
client tests

### ISSUE THREAD

**Issue by kalshett** [avocado-framework/avocado-misc-tests#8]
The readme says  tests ported from autotest client tests repository, so if that is the case can we name as client tests instead of Misc Tests?   

All that I'm looking for exact naming convention maintained in the autotest client tests to be available in Avocado framework. This would help us in moving from autotest -> avocado framework.

**Comment by clebergnu** [comment]
@kalshett Avocado doesn't make a distinction between client and server tests, so that's why we have named this repository simply "misc" tests. You could simply drop that identification.

**Comment by ldoktor** [comment]
Hello @kalshett , it's worth mention, that in the readme we say:

_This repository is dedicated to host any tests written using the avocado [1] API. It is being initially populated with tests ported from autotest client tests repository, but it's not limited by that._

so the purpose of this repository is not to port autotest tests, but to provide a share repo for various useful tests.

**Comment by kalshett** [comment]
Somehow "misc" naming seems to me as uncategorised. 

I'm primarily looking at linux operating system(OS) tests to be added as part of avocado framework, if that is the case then we can categorize as OS sub-components tests?(ex: mem, filesystem(fs), IO, scheduler etc)  under this "misc" ? or you suggest different git repo under avocado?

**Comment by sathnaga** [comment]
Sample directory structure can be like below?
.
├── cpu
│       ├── cpu_hotplug.py
│       └── cpu_hotplug.py.data
├── generic
├── io
│      ├── disk
│      │   ├── parallel_dd.py
│      │   └── parallel_dd.py.data
│      └── net
│             ├── netperf.py
│             └── netperf.py.data
├── mem
│       ├── memory_api.py
│       └── memory_api.py.data
└── perf

**Comment by kalshett** [comment]
+1;   I'm assuming these would be under "avocado-misc-tests" repo.

**Comment by apahim** [comment]
Yep, agreed.

**Comment by apahim** [comment]
Feel free to reclassify tests under `perf`. Also, notice we have now an asset fetcher, so no need to keep in the repository the downloadable files, like tarballs and so on:
http://avocado-framework.readthedocs.org/en/latest/WritingTests.html#fetching-asset-files

**Comment by kalshett** [comment]
yes, little bit of re-clarification is required for "perf". As not sure we really want to include
stress tests under "perf" bucket.

**Comment by ldoktor** [comment]
This repository is frozen, please re-raise this issue in https://github.com/avocado-framework-tests/avocado-misc-tests if still valid.
