### ISSUE TITLE
TODO:Port  xfstests Test from autotest to avocado

### ISSUE THREAD

**Issue by PraveenPenguin** [avocado-framework/avocado-misc-tests#85]
I am working on porting  xfstests  from autotest to avocado,
Link:"https://github.com/autotest/autotest-client-tests/tree/master/xfstests"

While porting facing some issue 
os_dep.library
os_dep.header

in autotest test code this function is used but in avocado i am not able get.
Can I implement these functionalities as common utilities to avocado, so able to use in my test?

**Comment by PraveenPenguin** [comment]
@ldoktor can please have a look into this issue

**Comment by ldoktor** [comment]
Hello @PraveenPenguin avocado is open source, of course we welcome any useful contribution and the `library`/`header` seem useful, although I'd probably use the `software_manager` to check/install packages, rather than check for missing header/library files.

**Comment by PraveenPenguin** [comment]
@ldoktor Thanks , tried with `software_manager` able to port the test
